### ISSUE TITLE
index.js is not loading details. Getting exception testResults is not iterable

### ISSUE THREAD

**Issue by jpranay** [dkelosky/jest-stare#45] opened 2018-12-06 20:12 UTC
I am generating html report programmatically. I am setting error when I am loading index.js. Here is the exception 
```
Uncaught TypeError: testResult.testResults is not iterable
    at results.testResults.forEach (view.js:273)
    at Array.forEach (<anonymous>)
    at Function.create (view.js:270)
    at Function.show (view.js:67)
    at HTMLDocument.document.addEventListener (view.js:50)
```
There is where I am seeing issue 
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Constants_1 = require("../Constants");
const Test_1 = require("../tests/Test");
class TestSuite {
    static create(results) {
        const elements = [];
        const describeLevels = [];
        results.testResults.forEach((testResult) => {
            let testStatusClass = Constants_1.Constants.PASSED_TEST;
            const testSectionStatus = new Map();
            for (const result of testResult.testResults) { ------- Exception 
```

**Comment by dkelosky** [comment] 2018-12-06 20:20
How are you invoking it programmatically?  I have one sample like this:
```typescript
// require jest-stare
const processor = require("jest-stare");

// load some jest results JSON data
const simplePassingTests = require("../__tests__/__resources__/simplePassingTests.json");

// call jest-stare processor, passing a first parm of the jest json results,
// and optionally a second parm of jest-stare config
processor(simplePassingTests, {log: false, resultDir: __dirname + "/output"});
```

Are you doing something similar?

**Comment by dkelosky** [comment] 2018-12-06 20:37
Thanks - also, what version of Node.js are you using?

**Comment by jpranay** [comment] 2018-12-06 21:03
I am using 
```
node v11.1.0
jest v23.6.0
```

**Comment by dkelosky** [comment] 2018-12-07 01:35
I'm not able to reproduce on my end.  What version of jest-stare are you using?

**Comment by dkelosky** [comment] 2018-12-07 01:38
Would it be possible to share your test's json?

**Comment by jpranay** [comment] 2018-12-07 19:46
I am using `jest-stare v1.8.0`. Here is my configuration for running jestCLI 
```
const options = {
	runInBand: true,
	projects: ['.'],
	testEnvironment: path.join(__dirname, 'test-environment.js'),
	testMatch: ['**/**/*.spec.js'],
	transform: {
		'^.+\\.jsx?$': 'babel-jest',
		"^.+\\.js$": "babel-jest"
	},
	verbose: true,
	json: true,
	outputFile: './results.json'
}
```

**Comment by dogboydog** [comment] 2018-12-07 20:10
@jpranay  I  believe he meant your test results JSON. If it's too big maybe you can put it on pastebin or  something. Thanks

**Comment by jpranay** [comment] 2018-12-07 21:51
@dkelosky  Here is my results json 

```{"numFailedTestSuites":2,"numFailedTests":4,"numPassedTestSuites":0,"numPassedTests":0,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTotalTestSuites":2,"numTotalTests":4,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1544219449486,"success":false,"testResults":[{"assertionResults":[{"ancestorTitles":["Example test suite for data driven test"],"failureMessages":["RequestError: Error: getaddrinfo ENOTFOUND read.qa.sams-caching-service.samsus.qa.walmart.com read.qa.sams-caching-service.samsus.qa.walmart.com:80\n    at new RequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.Object.<anonymous>.Request.onRequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:441:20)\n    at Socket.socketErrorListener (_http_client.js:399:9)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process.internalTickCallback (internal/process/next_tick.js:72:19)"],"fullName":"Example test suite for data driven test test for data 4925","location":null,"status":"failed","title":"test for data 4925"},{"ancestorTitles":["Example test suite for data driven test"],"failureMessages":["RequestError: Error: getaddrinfo ENOTFOUND read.qa.sams-caching-service.samsus.qa.walmart.com read.qa.sams-caching-service.samsus.qa.walmart.com:80\n    at new RequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.Object.<anonymous>.Request.onRequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:441:20)\n    at Socket.socketErrorListener (_http_client.js:399:9)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process.internalTickCallback (internal/process/next_tick.js:72:19)"],"fullName":"Example test suite for data driven test test for data 6612","location":null,"status":"failed","title":"test for data 6612"},{"ancestorTitles":["Example test suite for data driven test"],"failureMessages":["RequestError: Error: getaddrinfo ENOTFOUND read.qa.sams-caching-service.samsus.qa.walmart.com read.qa.sams-caching-service.samsus.qa.walmart.com:80\n    at new RequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.Object.<anonymous>.Request.onRequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:441:20)\n    at Socket.socketErrorListener (_http_client.js:399:9)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process.internalTickCallback (internal/process/next_tick.js:72:19)"],"fullName":"Example test suite for data driven test test for data 4795","location":null,"status":"failed","title":"test for data 4795"}],"endTime":1544219451430,"message":"\u001b[1m\u001b[31m  \u001b[1m● \u001b[1mExample test suite for data driven test › test for data 4925\u001b[39m\u001b[22m\n\n    RequestError: Error: getaddrinfo ENOTFOUND read.qa.sams-caching-service.samsus.qa.walmart.com read.qa.sams-caching-service.samsus.qa.walmart.com:80\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat new RequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/errors.js\u001b[39m\u001b[0m\u001b[2m:14:15)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.plumbing.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:87:29)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.RP$callback [as _callback] (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:46:31)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat self.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:185:22)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.Object.<anonymous>.Request.onRequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:881:8)\u001b[2m\u001b[22m\n\n\u001b[1m\u001b[31m  \u001b[1m● \u001b[1mExample test suite for data driven test › test for data 6612\u001b[39m\u001b[22m\n\n    RequestError: Error: getaddrinfo ENOTFOUND read.qa.sams-caching-service.samsus.qa.walmart.com read.qa.sams-caching-service.samsus.qa.walmart.com:80\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat new RequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/errors.js\u001b[39m\u001b[0m\u001b[2m:14:15)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.plumbing.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:87:29)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.RP$callback [as _callback] (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:46:31)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat self.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:185:22)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.Object.<anonymous>.Request.onRequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:881:8)\u001b[2m\u001b[22m\n\n\u001b[1m\u001b[31m  \u001b[1m● \u001b[1mExample test suite for data driven test › test for data 4795\u001b[39m\u001b[22m\n\n    RequestError: Error: getaddrinfo ENOTFOUND read.qa.sams-caching-service.samsus.qa.walmart.com read.qa.sams-caching-service.samsus.qa.walmart.com:80\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat new RequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/errors.js\u001b[39m\u001b[0m\u001b[2m:14:15)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.plumbing.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:87:29)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.RP$callback [as _callback] (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:46:31)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat self.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:185:22)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.Object.<anonymous>.Request.onRequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:881:8)\u001b[2m\u001b[22m\n","name":"/Users/p0j004n/Documents/work/sams-tests/tests/examples/specs/data-driven.spec.js","startTime":1544219450161,"status":"failed","summary":""},{"assertionResults":[{"ancestorTitles":["Demo test suite for e2e"],"failureMessages":["RequestError: Error: getaddrinfo ENOTFOUND api.qa.wal-mart.com api.qa.wal-mart.com:443\n    at new RequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.Object.<anonymous>.Request.onRequestError (/Users/p0j004n/Documents/work/star/packages/star/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:441:20)\n    at TLSSocket.socketErrorListener (_http_client.js:399:9)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process.internalTickCallback (internal/process/next_tick.js:72:19)"],"fullName":"Demo test suite for e2e Login with new member","location":null,"status":"failed","title":"Login with new member"}],"endTime":1544219451755,"message":"\u001b[1m\u001b[31m  \u001b[1m● \u001b[1mDemo test suite for e2e › Login with new member\u001b[39m\u001b[22m\n\n    RequestError: Error: getaddrinfo ENOTFOUND api.qa.wal-mart.com api.qa.wal-mart.com:443\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat new RequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/errors.js\u001b[39m\u001b[0m\u001b[2m:14:15)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.plumbing.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:87:29)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.RP$callback [as _callback] (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request-promise-core/lib/plumbing.js\u001b[39m\u001b[0m\u001b[2m:46:31)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat self.callback (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:185:22)\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Request.Object.<anonymous>.Request.onRequestError (\u001b[2m\u001b[0m\u001b[36m../../../star/packages/star/node_modules/request/request.js\u001b[39m\u001b[0m\u001b[2m:881:8)\u001b[2m\u001b[22m\n","name":"/Users/p0j004n/Documents/work/sams-tests/tests/examples/specs/e2e.spec.js","startTime":1544219451443,"status":"failed","summary":""}],"wasInterrupted":false}```

**Comment by dkelosky** [comment] 2018-12-07 23:02
Thanks - I'll pull this and give it a try tonight (hopefully) and let you know!

**Comment by dkelosky** [comment] 2018-12-08 13:48
Thanks for the test info, I reproduced your issue and will work on a fix :smiley:

**Comment by dkelosky** [comment] 2018-12-08 14:47
Documenting what we (working with a friend @dogboydog ) have so far. 

This doc is for Jest  results format: https://jestjs.io/docs/en/configuration#testresultsprocessor-string with and outer testResults array and inner testResults array.  Your tests have testResults with inner assertionResults.  I don't see this documented or know how to create these yet.

**Comment by dkelosky** [comment] 2018-12-08 15:35
https://github.com/facebook/jest/issues/7485 for reference

**Comment by jpranay** [comment] 2018-12-08 17:45
> testResultsProcessor

Thanks for the workaround. It worked for me

**Comment by dkelosky** [comment] 2018-12-08 18:34
Thanks, I opened #49.  I'll have a separate enhancement in the future to support assertionResults.  I'll close this one and track there if no objections.

**Closed** 2018-12-13 20:20 UTC
