### ISSUE TITLE
Cannot find module './doc/IJestStareConfig'

### ISSUE THREAD

**Issue by Ionut-Milas** [dkelosky/jest-stare#41] opened 2018-09-05 10:17 UTC
Hi guys.
I'm hitting this error: Cannot find module './doc/IJestStareConfig'
Any help would be greatly appreciated.
`Error: Cannot find module './doc/IJestStareConfig'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/jest-stare/lib/processor/Config.js:5:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by dogboydog** [comment] 2018-09-05 10:42
Hi,

When are you encountering this error? Installing or trying to run a report? Looks like you're trying to install with yarn maybe?

**Comment by Ionut-Milas** [comment] 2018-09-05 12:49
Hi,
The issue pops up after I run the specs. I think that it appears when it attempts to build the report.
The package is in dev-dependencies, installed with yarn, and added in jest.config.js as `testResultsProcessor: './node_modules/jest-stare'`

**Comment by dkelosky** [comment] 2018-09-06 10:33
Hi,

Do you have any "jest-stare" config in your package.json?  Also, can you share what version you're using of jest-stare?  

I haven't tested with yarn, but I'll see if this is reproduceable this morning. 

Thanks!

**Comment by dkelosky** [comment] 2018-09-06 16:26
I'm also wondering if the installation was successful.  In your `./node_modules/jest-start/lib/processor/doc` folder, what are the contents?

**Comment by caina-jumia** [comment] 2018-10-25 12:46
> Hi,
> 
> Do you have any "jest-stare" config in your package.json? Also, can you share what version you're using of jest-stare?
> 
> I haven't tested with yarn, but I'll see if this is reproduceable this morning.
> 
> Thanks!

I have installed and run with yarn and works fine!

**Comment by dkelosky** [comment] 2018-10-25 14:59
Thanks, I'll close this for now then!

**Closed by dkelosky** 2018-10-25 14:59 UTC
